
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 26 12:21:17 CST 2019
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENUP = 17;
  public static final int MENOS = 7;
  public static final int MULTIPLICACION = 8;
  public static final int CCERRADO = 31;
  public static final int IGUAL = 4;
  public static final int PCERRADO = 3;
  public static final int POSITIONXY = 20;
  public static final int DIVISION = 9;
  public static final int COLOR = 23;
  public static final int TOCENTER = 19;
  public static final int POSITIONY = 22;
  public static final int POSITIONX = 21;
  public static final int BACKWARD = 13;
  public static final int RIGHT = 15;
  public static final int FORWARD = 12;
  public static final int PENDOWN = 18;
  public static final int COMA = 10;
  public static final int LEFT = 14;
  public static final int EOF = 0;
  public static final int SHOWTURTLE = 25;
  public static final int TODRAW = 27;
  public static final int TOERASE = 26;
  public static final int NUMERO = 32;
  public static final int error = 1;
  public static final int CABIERTO = 30;
  public static final int IDENTIFICADOR = 29;
  public static final int PABIERTO = 2;
  public static final int HIDETURTLE = 24;
  public static final int CLEARS = 16;
  public static final int COMENTARIO = 5;
  public static final int HEXADECIMAL = 11;
  public static final int REPEAT = 28;
  public static final int MAS = 6;
}

